name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    # container:
    #   image: pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']
        torch-version: [2.6.0] 
        cuda-version: ['cu124']

    steps:
    # Add a step to set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Use a more recent version of actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add dependencies
      run: sudo apt-get install -y clang-format
    - uses: actions/checkout@v4 # Use a more recent version of actions/checkout
    - name: Check Lint
      run: bash tools/check_diff.sh
    # - name: Install dependencies
    #   run: bash tools/install_deps.sh
    # - name: Build af 
      # run: make -j af
    # - name: Build pip
      # run: python3 setup.py build
